-- Sounds.lua
-- Instance grouping + raid/heroic-only classification used by Config.lua
-- and Core.lua filter logic.  The actual sound table (per-clip files +
-- durations) lives in Snippets.lua, which is auto-generated by
-- assemble_addon_sounds.py.
--
-- Cooldowns are global now (per soundKey was the old per-pre-baked
-- model — new snippet-based system uses one cooldown per *sentence*
-- via db.cooldownGlobal in Core.lua).

LFGSpeakerNS = LFGSpeakerNS or {}
local ns = LFGSpeakerNS

ns.SOUND_BASE_PATH = "Interface\\AddOns\\LFGSpeaker\\sounds\\"

-- Cooldown bucket per-instance-key (used by Core.lua sentence-level CD).
-- Frequent ad-spam instances get longer cooldowns.
local SHORT = 20
local MED   = 45
local LONG  = 90

ns.INSTANCE_COOLDOWN = {
    ramp  = SHORT, bf   = SHORT, shh  = SHORT,
    sp    = SHORT, ub   = SHORT, sv   = SHORT,
    mt    = SHORT, auch = SHORT, seh  = SHORT, sl = SHORT,
    bot   = SHORT, mech = SHORT, arc  = SHORT,
    oh    = SHORT, bm   = SHORT, mgt  = SHORT,
    kara  = MED,   za   = MED,
    gruul = LONG,  magth = LONG, ssc  = LONG, tk = LONG,
    hyjal = LONG,  bt    = LONG, swp  = LONG,
}
ns.DEFAULT_COOLDOWN = SHORT

ns.RAID_KEYS = {
    kara = true, gruul = true, magth = true, ssc = true, tk = true,
    hyjal = true, bt = true, za = true, swp = true,
}

ns.HEROIC_ONLY_KEYS = {
    mgt = true,
}

ns.INSTANCE_GROUPS = {
    { name = "Hellfire Citadel",
      keys = { "ramp", "bf", "shh" } },
    { name = "Coilfang Reservoir",
      keys = { "sp", "ub", "sv" } },
    { name = "Auchindoun",
      keys = { "mt", "auch", "seh", "sl" } },
    { name = "Tempest Keep wings",
      keys = { "bot", "mech", "arc" } },
    { name = "Caverns of Time",
      keys = { "oh", "bm" } },
    { name = "Sunwell",
      keys = { "mgt" } },
    { name = "Raids",
      keys = { "kara", "gruul", "magth", "ssc", "tk", "hyjal", "bt", "za", "swp" } },
}
